import esbuild from 'esbuild';
import process from 'process';
import { copyFileSync, existsSync, mkdirSync } from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

function copyStyles() {
  if (!existsSync('dist')) {
    mkdirSync('dist', { recursive: true });
  }
  if (existsSync('styles.css')) {
    copyFileSync('styles.css', 'dist/styles.css');
    console.log('Copied styles.css to dist/');
  }
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
  minify: prod,
});

if (prod) {
  await context.rebuild();
  copyStyles();
  process.exit(0);
} else {
  copyStyles();
  await context.watch();
}
