import esbuild from 'esbuild';
import process from 'process';
import { copyFileSync, existsSync, mkdirSync, readFileSync } from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

function copyStyles() {
  if (!existsSync('dist')) {
    mkdirSync('dist', { recursive: true });
  }
  if (existsSync('styles.css')) {
    copyFileSync('styles.css', 'dist/styles.css');
  }
}

function loadEnv() {
  if (!existsSync('.env')) return;
  const content = readFileSync('.env', 'utf-8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex > 0) {
      const key = trimmed.slice(0, eqIndex).trim();
      const value = trimmed.slice(eqIndex + 1).trim();
      if (!process.env[key]) {
        process.env[key] = value;
      }
    }
  }
}

function deployLocal() {
  const targetDir = process.env.DEPLOY_TARGET_DIR;
  if (!targetDir) return;
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }
  copyFileSync('dist/main.js', `${targetDir}/main.js`);
  copyFileSync('dist/styles.css', `${targetDir}/styles.css`);
  copyFileSync('manifest.json', `${targetDir}/manifest.json`);
  console.log(`[deploy] -> ${targetDir}`);
}

loadEnv();

const deployPlugin = {
  name: 'deploy-plugin',
  setup(build) {
    build.onEnd(() => {
      copyStyles();
      deployLocal();
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
  minify: prod,
  plugins: prod ? [] : [deployPlugin],
});

if (prod) {
  await context.rebuild();
  copyStyles();
  process.exit(0);
} else {
  await context.watch();
}
